name:                wai-tutorial
version:             0.1.0.0
github:              "nsluss/wai-tutorial"
license:             BSD3
author:              "Noah Sluss"
maintainer:          "slussnoah@gmail.com"
copyright:           "2018 Noah Sluss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nsluss/wai-tutorial#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-types
- text
- wai
- warp

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  wai-tutorial-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-tutorial

tests:
  wai-tutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-tutorial
    - hspec
